### ISSUE TITLE
Tenho algumas dúvidas

### ISSUE THREAD

**Issue by gabrielbmoro** [lfgmillani/ReDFST#1]
Olá Luís Felipe, ingressei agora no mestrado sob a orientação do professor Lucas. Tenho algumas dúvidas sobre a biblioteca que desenvolveste, teria como conversarmos por e-mail.
Meu e-mail é gabrielbronzattimoro.es@gmail.com.
Abraço, desde já agradeço, desculpa atrapalhar.

**Comment by lfgmillani** [comment]
Oi,
Pode enviar as dúvidas para lfmillani@gmail.com ou lfgmillani@inf.ufrgs.br.

A+
