### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by schnorr** [lfgmillani/ReDFST#2]
Hi,
We have found some benchmarks that are written in Fortran. What should we do to use ReDFST with fortran code?
Best

**Comment by lfgmillani** [comment]
Hi,

You should be able to use it normally. If you're not using OpenMP with Fortran you'll have to call redfst_thread_init(thread_num) for each of the threads in the program. Notice that you won't be able to call redfst_region_all without OpenMP.
With OpenMP it should initialize each thread automatically.

Sample Fortran code:

```
      program foo
      interface
       subroutine redfst_thread_init(id)
     +  bind(c,name="redfst_thread_init")
        use iso_c_binding, only: c_int
        integer(c_int), value, intent(in) :: id
       end subroutine
       subroutine redfst_region(id)
     +  bind(c, name="redfst_region")
        use iso_c_binding, only: c_int
        integer(c_int), value, intent(in) :: id
       end subroutine redfst_region
      end interface
      call redfst_thread_init(0)
      call redfst_region(1)
      print *, "foo"
      redfst_region(2)
      print *, "bar"
      end program foo
```

You can compile and link with:

gfortran foo.f -lredfst -lcpufreq

I have not tested with Fortran, so let me know if something breaks.
